### ISSUE TITLE
Make release

### ISSUE THREAD

**Issue by fulldecent** [VanillaandCream/Catamaran-Tamil#12]
Please make a "release" for easy download for offline uses.

**Comment by VanillaandCream** [comment]
How do you suppose I should do this? Is it hard to download from Google Fonts?

**Comment by fulldecent** [comment]
The normal way is to click here https://github.com/VanillaandCream/Catamaran-Tamil/releases and then click new release.

Maybe this will be version 1.0.0. (You can use the "tag" name of `1.0.0`).

I still have not found out how to download from Google Fonts. But I am glad I found this repo. I was able to clone and extract the files.

Thanks for this beautiful font!

**Comment by VanillaandCream** [comment]
But you can also download instead of clone.

**Comment by fulldecent** [comment]
Closing, I don't think this is going to happen.

**Comment by davelab6** [comment]
Thanks for your effort to suggest this; I have plans to bring releases to
all GitHub.com/GoogleFonts repos and forks :)
