### ISSUE TITLE
Building binaries from sources

### ISSUE THREAD

**Issue by m4rc1e** [VanillaandCream/Catamaran-Tamil#16]
Hello,

I'm currently tasked with releasing the latest fonts onto Google Fonts. I may have to do some tweaks to the fonts metadata. In order for me to do this, I need to understand the build process.

I see we have 5 .glyphs files, catamaran–catamaran4. Ideally, we should have 1 file. The build should be self explanatory, or if it isn't, a shell script should run through the steps needed to build the fonts. 

so my question, which source .glyphs file was used to generate the .ttfs?

If multiple file are needed, a quick bullet point list of steps should be sufficient.

Regards,
Marc

**Comment by VanillaandCream** [comment]
Hi Marc., It doesn't matter which source file is used, they will work with the features fine in which way. Does this answer your question.

**Comment by m4rc1e** [comment]
Hey,

Ok, in that case I'll just use **Catamaran.glyphs**. I'll get back to you if I have further issues.
Thanks

**Comment by VanillaandCream** [comment]
Great, looking forward to it.

**Comment by VanillaandCream** [comment]
Marc, I ve just updated the Name Records table and pushed it on git. Hope that is okay.

**Comment by m4rc1e** [comment]
Ok,

Are you building the fonts with the AFDKO?

**Comment by VanillaandCream** [comment]
OTM, its built on AFDKO

**Comment by m4rc1e** [comment]
@davelab6 @VanillaandCream I'm tempted to port this completely to Glyphs. the features for Tamil are relatively simple. However, this will take me a day or so.

There is also no folder structure to allow me to build this with the afdko quickly. 

If we need it desperately, I can hot fix. Otherwise, I suggest we do this properly and leave it till January.

**Comment by VanillaandCream** [comment]
Marc, Catamaran has an optimized glyph set and is produced with components functioning to form ligatures. Do keep it in mind if you want to move to Glyphs.

**Comment by m4rc1e** [comment]
Ok,

Then I suggest we stick with the afdko.

Could you include the supplementary files in this repo to build the fonts. This is currently a bit of a mystery. A shell script which can run through all the steps needed (afdko build, autohinting etc) would be ideal.

**Comment by VanillaandCream** [comment]
I do it manually using OTM. I don't have a shell script at he moment, but I can certainly make one if you insist.

**Comment by m4rc1e** [comment]
Ahh sorry I've been an idiot. OTM as in the DTL tool :-)

Ok, I only use OTM lite to inspect fonts. A solution could be if I file issues on the metadata and you can apply the fixes yourself, then regenerate the fonts.

Is this approach ok for you?

If you don't have the time, I can always hot fix the binaries, or we can wait till January.

**Comment by VanillaandCream** [comment]
Of course I have time Marc, send me a list and I will update them.

**Comment by m4rc1e** [comment]
Fabulous. Thank you for your corporation with this. You have the patience of a saint. 

I'll submit them as an issue. Expect it tomorrow. 

Have a nice day!

**Comment by m4rc1e** [comment]
If i generate the .glyph files. I'm not able to import the gsub .fea in OTMaster. However, I'm able to import the .fea onto the preexisting fonts. This leads me to believe that the sources are incompatible.

![screen shot 2016-12-17 at 11 22 41](https://cloud.githubusercontent.com/assets/7525512/21310449/b9934b0e-c5e2-11e6-8d49-f54c063d5ad4.png)


I may just send you the name table data separately.

Cheers,
Marc

**Comment by VanillaandCream** [comment]
Are the postscript names exported? Its possibly due to that. Please check
again.

**Comment by m4rc1e** [comment]
Hey,

Yep, it was a long those lines :-)

When you generate a font with Glyphs, it will change the glyph names so they're production friendly. When I disabled this feature, the OTM .fea files worked.

I'll close this for now. 

Thank you for your help!

**Comment by VanillaandCream** [comment]
Great.
