### ISSUE TITLE
char problem: ü, ö

### ISSUE THREAD

**Issue by saitergun** [VanillaandCream/Catamaran-Tamil#19]
![catamaran-problem](https://cloud.githubusercontent.com/assets/6763507/22826267/93924718-efa2-11e6-8680-88dfb2b963c9.jpg)

thank you first for this amazing font. really good. but, there is a tiny problem. marked picture.

**Comment by qlymax** [comment]
The font on google fonts isn't updated. The version on Github has fixed this problem.

**Comment by saitergun** [comment]
@qlymax thanks for info. i'm using on web this font. when is update on google fonts?

**Comment by qlymax** [comment]
Google said to us 'End of January '17' But nothing changed so far.

**Comment by saitergun** [comment]
@qlymax understand you. thanks for backs.

**Comment by m4rc1e** [comment]
Its fixed now:

![screen shot 2017-06-22 at 12 06 38](https://user-images.githubusercontent.com/7525512/27431133-4c990424-5743-11e7-883f-470fc25e2bc3.png)

**Comment by davelab6** [comment]
The regular style in that image is broken

**Comment by m4rc1e** [comment]
@davelab6 good spot!

**Comment by m4rc1e** [comment]
cc @VanillaandCream

**Comment by saitergun** [comment]
Regular style should be 2 dots

**Comment by VanillaandCream** [comment]
[image: Inline image 1]
Looks fine, where are you seeing?

**Comment by saitergun** [comment]
on google fonts https://fonts.google.com/specimen/Catamaran
please type "üö" on preview text input.

we have talked about this. waiting google fonts team for update this font.

**Comment by VanillaandCream** [comment]
I have no clue what versions you guys push., this is from my latest git
repo.

[image: Inline image 2][image: Inline image 1]

**Comment by m4rc1e** [comment]
I see the issue,

fonts.google.com is using v1.000, whilst the repo contains v1.100. The v1.100 still needs to be pushed into production but it has been pr'd and merged:
https://github.com/google/fonts/pull/716

**Comment by VanillaandCream** [comment]
Do I have to do anything?

**Comment by m4rc1e** [comment]
Nope, I'm closing this. This issue is a none issue, once the new files come into production.

**Comment by VanillaandCream** [comment]
Awesome.
