### ISSUE TITLE
Weight Axis variable font

### ISSUE THREAD

**Issue by pichotta** [VanillaandCream/Catamaran-Tamil#29]
@VanillaandCream

Hello Pria,

The Google fonts team would love to see a variable font version of ‘Catamaran'. They have commissioned us @TypeNetwork to work on upgrading a number of font projects to be variable fonts with a single weight axis.

In order to achieve the highest quality and most efficient long term results we will be converting the source data from Glyphs to UFO. The new source data will be generated in the RoboFont environment using fontmake and ttfautohint. There has been progress on tools to make an easy path to move between the Glyphs and Robofont environment.

During the process we will be looking to improve any errors while preserving how the font appears and renders on different platforms.

We have started by making a fork off of this git repository which can be found here in the  'ufo-conv' branch. https://github.com/TypeNetwork/Catamaran-Tamil/tree/ufo-conv

We are not quite sure how these four Glyphs sources are organized?
Catamaran1.glyphs
Catamaran2.glyphs
Catamaran3.glyphs
Catamaran4.glyphs

Each of these .glyphs files have different instances with different Axes Coordinate values? Does 
1 contain Thin and ExtraLight and Light?
2 contain Regular and Medium?
3 contain Semibold and Bold?
4 contain ExtraBold and Black?

It looks like Light and Bold are the Masters. Is there a reason the instances are not combined into one source file? Thank you for any information.

The upgrade will be completed for you in the near future. When the proposed final font is approved by Google they will accept a pull request.

We hope this answers some of your questions about the process. Please let us know if you have any additional comments.

Best Regards,

Jill Pichotta
Vice President
Type Network
pichotta@typenetwork.com

![Catamaran Instances 2019-12-17 at 5 40 10 PM](https://user-images.githubusercontent.com/6576107/71040649-1931ec80-20f5-11ea-8583-5c4251e95dbc.png)

**Comment by VanillaandCream** [comment]
Hi Jill,
 Catamaran is a mess. I was just figuring out glyphs when i started working
on it. The last instance in each file overlaps with the first instance in
the next. If Catamaran has to be made variable, it might need to be changed
and cleaned up. Please let me know if I can help.

Best Regards
Pria

**Comment by pichotta** [comment]
@VanillaandCream

Hello Pria,

The work on the weight axis variable font for Catamaran-Tamil is complete and has been integrated upstream. 

https://github.com/TypeNetwork/Catamaran-Tamil/tree/master/fonts/variable

https://github.com/google/fonts/pull/2547


Best,

Jill
