### ISSUE TITLE
Ellipsis ligature looks like a single dot

### ISSUE THREAD

**Issue by felipelavinz** [VanillaandCream/Catamaran-Tamil#5]
Hi!

I've noticed that the ellipsis (`...`) ligature looks like a single dot, but instead it should look like three separate dots.

![4931382201](https://cloud.githubusercontent.com/assets/144856/10637957/d7c46be2-77de-11e5-95b3-d22689277a7f.png)

I'm using the Google Fonts version, so I don't know if that's an issue with that particular version.

I really enjoy your font, thanks for the amazing work!

**Comment by VanillaandCream** [comment]
Hi, thanks for the observation. I just resolved it.

**Comment by davelab6** [comment]
(in https://github.com/VanillaandCream/Catamaran-Tamil/commit/3a6e9871bc4752046675da4fb4714aea7be4ba63)

**Comment by felipelavinz** [comment]
Great, thanks!
